lint:
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - .github/workflows/linting_comment.yml
  files_unchanged:
    - .github/PULL_REQUEST_TEMPLATE.md
    - docs/images/nf-core-proteinfamilies_logo_light.png
    - docs/images/nf-core-proteinfamilies_logo_dark.png
    - .github/workflows/branch.yml
    - .github/workflows/linting.yml
nf_core_version: 4.1.0
repository_type: pipeline
template:
  author: Evangelos Karatzas
  description: Generate protein family level models (Multiple Sequence Alignments (MSAs), Hidden Markov Models (HMMs)) starting from a FASTA amino acid sequence file.
  force: false
  is_nfcore: true
  name: proteinfamilies
  org: nf-core
  outdir: .
  skip_features:
    - igenomes
    - fastqc
  version: 2.6.0dev
